name: CI/CD to Kubernetes

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ✅ Fixes Node.js warning and creditial update2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/education2:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/education2:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_FINAL }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_FINAL }}
          script: "KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl set image deployment/education2-deployment education2=${{ secrets.DOCKER_USERNAME }}/eduaction2:latest"
